### ISSUE TITLE
Installation of moogli (No PYQT4_SIP_FLAGS found.  Can't continue)

### ISSUE THREAD

**Issue by schm9596** [BhallaLab/moose#239] opened 2018-07-31 03:18 UTC
I am trying to install moose on a Centos 7 machine. I have installed everything successfully up to moogli. I can run examples in the python shell.

I installed all the dependency successfully with:
$ sudo yum install sip-devel PyQt4-devel qt4-devel libjpeg-devel PyQt4 

Then I entered the following to install moogli in the moogli folder:
$ mkdir _build
$ cd _build
$ cmake ..

I get the following error:

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonDev: /usr/bin/python-config  
++ Found SIP flags: 
CMake Error at CMakeLists.txt:26 (MESSAGE):
  ++ No PYQT4_SIP_FLAGS found.  Can't continue

I have pyqt4 installed with python 2.7. 

Thanks for the help.

**Comment by dilawar** [comment] 2018-07-31 04:10
I was able to build moogli on a fresh docker image of centos-7. However, I had epel repos enabled and I was using `cmake3`. I could not get configuration done with default cmake.

~~~
# yum install epel-release
# yum update
# yum install cmake3
# cmake3 ..
# make -j4  # parallel build
~~~

If this  fails let me know. MOOGLI is likely to cause headache. We have success only on Ubuntu/Debian machines with MOOGLI.

Importantly MOOGLI is no longer maintained actively.  And there is plan to drop it in favor of matplotlib/d3js which is a work in progress.

**Comment by schm9596** [comment] 2018-07-31 16:01
I got the same error again after the following:

$ yum install epel-release
$ yum update
$ yum install cmake3
$ mkdir _build
$ cd _build
$ cmake3 ..

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonDev: /usr/bin/python-config  
++ Found SIP flags: 
CMake Error at CMakeLists.txt:26 (MESSAGE):
  ++ No PYQT4_SIP_FLAGS found.  Can't continue

**Comment by dilawar** [comment] 2018-08-01 01:57
Download this file https://raw.githubusercontent.com/BhallaLab/moogli/master/moogli/cmake_modules/FindPyQt4.py and run it. Post the output,

      $ python FindQt4.py

**Comment by dilawar** [comment] 2018-08-01 04:30
I used following bash script on a fresh docker image of centos-7.

```
if [ ! -d  moogli ]; then 
        git clone https://github.com/BhallaLab/moogli --depth 50 
fi 
sudo yum install epel-release -y 
sudo yum install git cmake3 python-devel gcc-c++ -y 
sudo yum install sip-devel PyQt4-devel qt4-devel libjpeg-devel PyQt4 -y 
sudo yum groupinstall 'Development Tools' -y 
( 
        cd moogli 
        mkdir -p _build 
        cd _build 
        cmake3 .. 
        make -j4 
)
```
Build was successful.

**Comment by dilawar** [comment] 2018-08-02 05:56
I've successfully build package for CentOS: It should be available here https://software.opensuse.org//download.html?project=home%3Amoose&package=moogli  . Install it from here, Let me know if something breaks. 

You can see [the build log for CentOS-7 here.](https://build.opensuse.org/package/live_build_log/home:moose/moogli/CentOS_7/x86_64) to debug your problem. Unfortunately I can't reproduce your error on any of my CentOS-7 environments (cluster, Docker Image, Open Build Service). I guess this problem is local to your machine.

I am closing this ticket but feel free to reopen it.

**Closed by dilawar** 2018-08-02 05:56 UTC
