### ISSUE TITLE
Negative Concentration in reaction diffusion simulation

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#164] opened 2015-04-28 14:00 UTC
Updated MOOSE and found that reaction diffusion simulation is giving negative concentration for the Lotka-volterra model. Have stripped down the code and attached.

Reported by: sahilm89

**Comment by dilawar** [comment] 2015-08-25 10:37
Not able to reproduce the bug. I believe it has been fixed. Closing for now.

**Closed by dilawar** 2015-08-25 10:37 UTC
Labels: auto-migrated
